---
# tasks file for tinyproxy
- name: Install tinyproxy
  apt:
    name: tinyproxy
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: Copy tinyproxy configuration
  copy:
    src: files/tinyproxy.conf
    dest: /etc/tinyproxy.conf
    owner: root
    mode: 0644

- name: Restart tinyproxy
  systemd:
    name: tinyproxy.service
    state: restarted
