---
# tasks file for nfs-server
- name: install nfs-common
  apt:
    name:
      - nfs-kernel-server
      - acl
    state: present

- name: enable the nfs-server
  systemd:
    name: nfs-kernel-server.service
    enabled: true

- name: ensure redteam group exists
  group:
    name: redteam
    state: present

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: root
    group: redteam
  loop: "{{ directories }}"

- name: configure export file
  template:
    src: templates/exports.j2
    dest: /etc/exports
    mode: 0644
    owner: root
    group: root

- name: restart nfs
  systemd:
    name: nfs-kernel-server.service
    state: restarted

- name: set acls for directories
  acl:
    default: true
    entity: redteam
    etype: group
    permissions: rwX
    state: present
    recursive: true
    path: "{{ item }}"
  loop: "{{ directories }}"
