---
- name: Configure sketch hosts
  hosts: all
  become: yes

  vars:
    required_ports:
      - 22
      - 80
      - 443
      - 2222
    ansible_command_timeout: 90

  tasks:
    - name: Append IP of each host to a local temporary file
      local_action:
        module: lineinfile
        path: "ansible_ips.txt"
        line: "{{ ansible_facts['default_ipv4']['address'] }}"
        create: yes
      run_once: false
      become: no

    - name: Set the hostname
      hostname:
        name: "{{ inventory_hostname }}"

    # update/upgrade/install packages
    - name: update/upgrade
      apt:
        update_cache: yes
        upgrade: dist
    - name: install apt packages
      apt:
        name:
          - unattended-upgrades
          - nginx

    - name: create user
      user:
        name: user
        password: "*"
        shell: /bin/bash
        create_home: yes
        state: present
    - name: add key to user
      authorized_key:
        user: user
        state: present
        key: "{{ lookup('file', '{{ ssh_pub_key }}') }}"
    - name: created sudoers.d/user
      copy:
        dest: /etc/sudoers.d/99user
        owner: root
        group: root
        mode: '0600'
        content: |
          user ALL=(ALL) NOPASSWD:ALL
    - name: create sketchssh
      user:
        name: sketchssh
        password: "*"
        create_home: yes
        shell: /bin/bash
        state: present

    - name: disable ssh password auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication yes'
        line: 'PasswordAuthentication no'
      notify:
      - reload sshd
    - name: disabled ssh pam
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?UsePAM yes'
        line: 'UsePAM no'
      notify:
      - reload sshd
    - name: disable password auth with pam
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?ChallengeResponseAuthentication yes'
        line: 'ChallengeResponseAuthentication no'
      notify:
      - reload sshd

    - name: Read IPs from the local temporary file
      local_action:
        module: command
        cmd: cat ansible_ips.txt
      register: ip_output
      become: no

    - name: Allow all ips in ip_output in ufw
      ufw:
        rule: allow
        from_ip: "{{ item }}"
      with_items: "{{ ip_output.stdout_lines }}"

    - name: Open required ports
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items: "{{ required_ports }}"

    - name: Block incoming/outgoing ipv6
      ufw:
        rule: deny
        proto: ipv6
        direction: "{{ item }}"
      with_items:
        - in
        - out

    - name: enable ufw
      ufw:
        state: enabled

    - name: replace root user in ssh configuration
      become: no
      replace:
        path: "{{ ssh_config_path }}"
        regexp: '(?<=User )root'
        replace: 'user'
      delegate_to: localhost

    - name: Clean up temporary file
      local_action:
        module: file
        path: "ansible_ips.txt"
        state: absent
      become: no

  handlers:
    - name: reload sshd
      service:
        name: sshd
        state: reloaded

