---
# tasks file for oci
- name: Stop resovled
  systemd:
    name: systemd-resolved.service
    state: stopped

- name: Disable resovled
  systemd:
    name: systemd-resolved.service
    enabled: false

- name: Mask resolved
  systemd:
    name: systemd-resolved.service
    masked: true

- name: Add dns server
  template:
    src: templates/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    mode: 0644

- name: Block access to vcn DNS resolver
  iptables:
    action: insert
    chain: OUTPUT
    destination: 169.254.169.254/32
    protocol: "{{ item }}"
    destination_port: "53"
    jump: DROP
    state: present
    comment: "disable access to OCI's VCN DNS resolver"
  with_items: ["tcp", "udp"]

- name: Save iptables
  command: iptables-save -f /etc/iptables/rules.v4
