---
# tasks file for ssh-proxy
- name: copy ssh-proxy tool
  copy:
    src: files/
    dest: /opt/ssh-proxy/
    owner: root
    group: root

- name: create ssh key folder
  file:
    path: /opt/ssh-proxy/keys
    owner: root
    mode: 0755
    state: directory

- name: generate ssh-keypair
  openssh_keypair:
    path: /opt/ssh-proxy/keys/sketchkey
    type: rsa
    state: present
