---
# tasks file for google-chrome
- name: Import Google Chrome's GPG key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Add Google Chrome's repository
  apt_repository:
    repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
    state: present

- name: Update apt and install Google Chrome
  apt:
    name: google-chrome-stable
    state: latest
    update_cache: yes
