---
- name: install build essential so we can compile nmap
  apt:
    name:
      - build-essential
  
- name: Download nmap source
  get_url:
    url: "https://nmap.org/dist/nmap-{{ nmap_version }}.tar.bz2"
    dest: "{{ tmp_path }}"
  
- name: Extract nmap source
  unarchive:
    src: "/tmp/nmap.tar.bz2"
    dest: "{{ src_path }}"
    remote_src: yes
    creates: "{{ src_path }}/nmap-{{ nmap_version }}"

- name: configure nmap
  command: "./configure"
  args:
    chdir: "{{ src_path }}/nmap-{{ nmap_version }}"
  
- name: build nmap
  make:
    chdir: "{{ src_path }}/nmap-{{ nmap_version }}"
  
- name: install nmap
  make:
    chdir: "{{ src_path }}/nmap-{{ nmap_version }}"
    target: "install"
  
- name: clean up src-directory
  file:
    path: "{{ src_path }}/nmap-{{ nmap_version }}"
    state: absent
  
- name: clean up download
  file:
    path: "{{ tmp_path }}"
    state: absent
