---
# tasks file for homebase
- name: install base packages for homebase
  apt:
    name:
      - asciinema
      - xfce4
      - xfce4-goodies
      - tigervnc-standalone-server
      - tigervnc-viewer
      - zile
      - emacs
      - firefox
      - nmap
      - nikto
      - xclip
      - proxychains4
    state: present

- name: setup-xfce4-vnc
  copy:
    src: files/setup-xfce4-vnc
    dest: /usr/local/bin/setup-xfce4-vnc
    owner: root
    group: root
    mode: 0755

- name: hashit
  copy:
    src: files/hashit
    dest: /usr/local/bin/hashit
    owner: root
    group: root
    mode: 0755

- name: implant_cryptor
  copy:
    src: files/implant_cryptor.py
    dest: /usr/local/bin/implant_cryptor
    owner: root
    group: root
    mode: 0755

- name: Remove firefox snap
  community.general.snap:
    name: firefox
    state: absent

- name: remove firefox apt package
  ansible.builtin.apt:
    name: firefox
    state: absent

- name: Add mozzila repository from PPA and install its signing key
  ansible.builtin.apt_repository:
    repo: ppa:mozillateam/ppa

- name: update package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install the firefox from ppa
  ansible.builtin.apt:
    name: firefox

- name: 51unattended-upgrades-firefox
  copy:
    src: files/51unattended-upgrades-firefox
    dest: /etc/apt/apt.conf.d/51unattended-upgrades-firefox
    owner: root
    group: root
    mode: 0755

- name: pin-firefox
  copy:
    src: files/mozilla-firefox
    dest: /etc/apt/preferences.d/mozilla-firefox
    owner: root
    group: root
    mode: 0755
