---
# tasks file for homebase
- name: install base packages for homebase
  apt:
    name:
      - asciinema
      - xfce4
      - xfce4-goodies
      - tigervnc-standalone-server
      - tigervnc-viewer
      - zile
      - emacs
      - firefox
      - nmap
      - nikto
      - xclip
      - proxychains4
    state: present

- name: setup-xfce4-vnc
  copy:
    src: files/setup-xfce4-vnc
    dest: /usr/local/bin/setup-xfce4-vnc
    owner: root
    group: root
    mode: 0755

- name: ensure polkit path exists
  file:
    path: /etc/polkit-1/localauthority/50-local.d
    state: directory
    recurse: yes
    mode: 0755

- name: xfce color profile
  copy:
    src: files/45-allow-colord.pkla
    dest: /etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla
    mode: 0755

- name: Restart polkit
  systemd:
    name: polkit
    state: restarted

- name: hashit
  copy:
    src: files/hashit
    dest: /usr/local/bin/hashit
    owner: root
    group: root
    mode: 0755

- name: implant_cryptor
  copy:
    src: files/implant_cryptor.py
    dest: /usr/local/bin/implant_cryptor
    owner: root
    group: root
    mode: 0755
