---
- name: Update apt and upgrade
  apt:
    update_cache: yes
    upgrade: dist

- name: Install software common to all hosts
  apt:
    name:
      - python3-pip
      - screen
      - tmux
      - iptables-persistent
      - vim
    state: present

- name: Setup skel
  copy:
    src: files/vimrc
    dest: /etc/skel/.vimrc

- name: Add vim to alternatives
  command:
    cmd: update-alternatives --install /usr/bin/editor editor /usr/bin/vim 0

- name: Configure vim as default text editor
  command:
    cmd: update-alternatives --set editor /usr/bin/vim

- name: Allow 192.168.0.0/16
  iptables:
    action: insert
    chain: "{{ item }}"
    jump: ACCEPT
    source: 192.168.0.0/16
    destination: 192.168.0.0/16
  loop:
    - INPUT
    - OUTPUT

- name: Save iptables
  command: iptables-save -f /etc/iptables/rules.v4

- name: Flush ip6tables rules
  command: ip6tables -F

- name: DROP INPUT, FORWARD, and OUTPUT chains for ipv6
  command: ip6tables -P {{ item }} DROP
  loop:
    - INPUT
    - FORWARD
    - OUTPUT

- name: Save ip6tables
  command: ip6tables-save -f /etc/iptables/rules.v6

- name: Update hostnames if required
  hostname:
    name: "{{ inventory_hostname }}"
  when: ansible_facts.hostname != inventory_hostname

- name: Update facts if required
  setup:
    filter:
      - 'ansible_hostname'
  when: ansible_facts.hostname != inventory_hostname

- name: /etc/hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    mode: 0644
    backup: true
