---
- name: update apt and upgrade
  apt:
    update_cache: yes
    upgrade: dist

- name: install software common to all hosts
  apt:
    name:
      - python3-pip
      - screen
      - tmux
      - iptables-persistent

- name: allow 192.168.0.0/16
  iptables:
    action: insert
    chain: "{{ item }}"
    jump: ACCEPT
    source: 192.168.0.0/16
    destination: 192.168.0.0/16
  loop:
    - INPUT
    - OUTPUT

- name: save iptables
  command: iptables-save -f /etc/iptables/rules.v4

- name: permanently disable IPv6
  copy:
    dest: /etc/default/grub.d/99-disable-ipv6.cfg
    content: |
      GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT ipv6.disable=1"

- name: update grub to disable IPv6 on reboot
  command: update-grub

- name: update hostnames if required
  hostname:
    name: "{{ inventory_hostname }}"
  when: ansible_facts.hostname != inventory_hostname

- name: update facts if required
  setup:
    filter:
      - 'ansible_hostname'
  when: ansible_facts.hostname != inventory_hostname

- name: /etc/hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    mode: 0644
    backup: true
