---
- name: update apt and upgrade
  apt:
    update_cache: yes
    upgrade: dist

- name: install software common to all hosts
  apt:
    name:
      - python3-pip
      - screen
      - tmux

- name: /etc/hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    backup: true
