---
# tasks file for homebase
- name: install packages
  apt:
    name:
      - asciinema
      - xfce4
      - xfce4-goodies
      - tigervnc-standalone-server
      - tigervnc-viewer
      - zile
      - emacs
      - firefox
      - nmap
      - nikto
      - xclip
      - proxychains4
    state: present

- name: setup-xfce4-vnc
  copy:
    src: files/setup-xfce4-vnc
    dest: /usr/local/bin/setup-xfce4-vnc
    owner: root
    group: root
    mode: 0755

- name: dot_screensaver
  copy:
    src: files/dot_screensaver
    dest: /usr/local/lib/dot_screensaver
    owner: root
    group: root
    mode: 0755

- name: hashit
  copy:
    src: files/hashit
    dest: /usr/local/bin/hashit
    owner: root
    group: root
    mode: 0755

- name: implant_cryptor
  copy:
    src: files/implant_cryptor
    dest: /usr/local/bin/implant_cryptor
    owner: root
    group: root
    mode: 0755
