---
# tasks file for etherpad
- name: Create user etherpad
  user:
    name: etherpad
    uid: 5001
    home: /opt/etherpad
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    state: present

- name: Create etherpad data directory
  file:
    path: /opt/etherpad/etherpad_data
    owner: etherpad
    group: etherpad
    mode: 0755
    state: directory
    recurse: true

- name: Copy docker-compose.yml
  copy:
    src: files/docker-compose.yml
    dest: /opt/etherpad/docker-compose.yml
    owner: etherpad
    group: etherpad
    mode: 0600

- name: Run docker-compose etherpad
  command: docker compose up -d
  args:
    chdir: /opt/etherpad
