---
- name: Install dante server
  apt:
    name:
      - dante-server
    state: present

- name: Generate dante configuration
  template:
    src: templates/danted.conf.j2
    dest: /etc/danted.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - Restart dante
