---
- name: Increase vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
    reload: true

- name: Create elk directory
  file:
    path: /opt/elk/
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Create Docker Compose template
  template:
    src: templates/docker-compose.yml.j2
    dest: /opt/elk/docker-compose.yml
    mode: 0644
    owner: root
    group: root

- name: Run docker-compose ELK stack
  command: docker compose up -d
  args:
    chdir: /opt/elk