- name: Add download.docker.com GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker.com repo
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name:
    - docker-ce
    - docker-compose-plugin
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: yes
