version: '3'
services:
  etherpad:
    image: etherpad/etherpad
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - ./etherpad_data:/opt/etherpad-lite/var
    user: etherpad
